### ISSUE TITLE
Error, Kali 2016 Rolling Release

### ISSUE THREAD

**Issue by lgcambero** [killswitch-GUI/SimplyEmail#11] opened 2016-04-17 20:16 UTC
![screenshot from 2016-04-17 17-14-14](https://cloud.githubusercontent.com/assets/11602705/14589749/054fbfda-04c0-11e6-83b3-f7eaf8c023d1.png)
Thanks!!

**Comment by killswitch-GUI** [comment] 2016-04-18 17:15
Hey @lgcambero,

It seems like it can't pull the right version. This may be do to a few things, could you please do a "git pull" and re-run the ./Setup.sh script and report back with any issues?

**Comment by lgcambero** [comment] 2016-04-18 17:42
I did everything as you indicated, but the error remains the same, any other ideas? please help me, I need the tool to the next class. :(

**Comment by killswitch-GUI** [comment] 2016-04-18 17:56
Yea in some rare cases Git could clober the repo. As of right now on a Kali 2.0 out of the box SimplyEmail runs and starts up. Please try to 
`rm -rf SimplyEmail ` repo
& 
`git clone https://github.com/killswitch-GUI/SimplyEmail.git`
than go ahead and try to run: 
`./SimplyEmail.py -l`

If this does not work we can dig deeper. Some times its something simple

**Comment by lgcambero** [comment] 2016-04-18 18:09
I am losing hope...

![sin titulo](https://cloud.githubusercontent.com/assets/11602705/14614415/77a45b10-0577-11e6-804d-3d2c373f315d.jpg)

**Comment by killswitch-GUI** [comment] 2016-04-18 18:22
Which one are you on so I can reproduce: https://www.kali.org/downloads/

Dont worry lol, prob a package issue with rolling Debian.

**Comment by lgcambero** [comment] 2016-04-18 18:23
http://cdimage.kali.org/kali-2016.1/kali-linux-2016.1-amd64.iso

Help me please!!!!

**Comment by killswitch-GUI** [comment] 2016-04-18 20:32
Downloading now will report back with a fix.

**Comment by killswitch-GUI** [comment] 2016-04-18 21:06
@lgcambero please run:
`uname -a` and report back with the results. As of right now on a clean image and install I can not reproduce the issue. Also make sure you 
`apt-get update`
`apt-get upgrade` 
and test as well

**Comment by killswitch-GUI** [comment] 2016-04-18 21:27
Pip has had issues in the past, maybe re install PIP 
`pip install -U pip`
and try `pip install configparser --upgrade`

**Comment by killswitch-GUI** [comment] 2016-04-18 21:27
Im thinking you cant read the SimplyEmail.ini

**Comment by lgcambero** [comment] 2016-04-19 14:25
Thanks for the help, none of the answers work for me. I have everything updated. The error persists.
![sin titulo](https://cloud.githubusercontent.com/assets/11602705/14642592/5f963f52-0621-11e6-80f2-184410735bb7.jpg)

**Comment by killswitch-GUI** [comment] 2016-04-19 21:53
@lgcambero at this point I don’t know how to reproduce the error your receiving. I’m thinking it may be environmental to a setting or package installed on your system that I cant reproduce. If possible could you try a clean install of the rolling Kali or Debian image. I have tested on all 3 clean distros with no issues. Im sorry I couldn’t figure out what was causing this!

**Comment by FastandLight** [comment] 2016-04-20 14:34
I believe this has to do with some of the dependencies. I was having this issue this morning with Pillow. Once I fixed that it installed, though it still doesn't actually run properly.

**Comment by killswitch-GUI** [comment] 2016-04-20 15:19
@FastandLight Yes this just took place for me too. It has to do with Pillow not installing properly. Hunting it down at lunch today! Thats for the report.

**Comment by lgcambero** [comment] 2016-04-20 15:21
Good news, I await the solution...

2016-04-20 12:19 GMT-03:00 Alexander Rymdeko-Harvey <
notifications@github.com>:

**Comment by FastandLight** [comment] 2016-04-20 16:15
The following worked for me to get Pillow installed.

```
sudo apt-get install python-dev python-setuptools libtiff5-dev  zlib1g-dev libfreetype6-dev liblcms2-dev libwebp-dev tcl8.6-dev tk8.6-dev python-tk
pip install --upgrade Pillow
```
Then Setup.sh was able to complete successfully, but after that, it still doesn't run right:

![image](https://cloud.githubusercontent.com/assets/18576812/14681990/7eecde6c-06f1-11e6-89c5-8224f10df283.png)

**Comment by killswitch-GUI** [comment] 2016-04-20 16:47
@FastandLight fixed the pillow install issues which are new. Still cant reproduce this error.. are you on kali 2.0?

**Comment by killswitch-GUI** [comment] 2016-04-20 16:53
@FastandLight please, rm -rf the dir, clone SimplyEmail, run the setup.sh script and try to run 
`python2.7 ./SimplyEmail.py -l`
Thanks!

**Comment by FastandLight** [comment] 2016-04-20 17:15
Kali-rolling. 

I just stood up a clean VM from the download image (without updating) to try things out. Was still broken. I'll try your fix in just a minute.

**Comment by FastandLight** [comment] 2016-04-20 17:57
Works now. I'll try on my fully updated machine in a moment.

**Comment by FastandLight** [comment] 2016-04-20 18:00
Still broken on my fully up to date Kali image. I'm going to take a snapshot of my working one, update, and see what happens.

**Comment by killswitch-GUI** [comment] 2016-04-20 18:03
@FastandLight ok sounds good, this is tracing back to the python-pptx module. Its weired how it works fine for all my boxes, even the download from Kali-rolling (VM)

**Comment by FastandLight** [comment] 2016-04-20 18:04
Did you run a full update on the Kali rolling box after downloading it
before trying?

Jeff Bolle

*SVP Technology*
*Q6 Cyber*
*(e)* jbolle@q6cyber.com
*(c) *757-301-1775 <617%20519%209288>

**Comment by killswitch-GUI** [comment] 2016-04-20 18:07
I just cloned and it worked. Doing full apt-get update/upgrade now

**Comment by FastandLight** [comment] 2016-04-20 18:09
Yeah, I think one of the dependencies gets impacted by a newer version or something when updating.

**Comment by killswitch-GUI** [comment] 2016-04-20 18:12
After the Update it still wored fine. Maybe I need to update/upgrade than try to install

**Comment by killswitch-GUI** [comment] 2016-04-20 20:40
Finally got the issue to produce. Looking into the regression now

**Comment by FastandLight** [comment] 2016-04-20 22:14
Glad to know we weren't crazy.

**Comment by killswitch-GUI** [comment] 2016-04-20 23:35
@FastandLight @lgcambero Please git pull and re run Setup.sh script!

It appears that during `apt-get dist-upgrade ` that Kali-rr installs the configparser from the `apt` package. After testing this issue out it appears it can be fixed by first removing config parser: `sudo apt-get remove python-configparser`. Turns out this was a isolated issue to Kali, since they install configparser during install to python 2.7.11+ in the last dist update. This caused pip to think it was installed and not installing during setup. I will be reporting this bug to Kali as well, thanks for bearing with me on this guys!

**Comment by rhertzog** [comment] 2016-04-21 07:31
I think you have not yet found the root cause of your issue. I would look into incompatibilities between what you install with pip and what gets installed via the debian packaging system. Best to not use pip outside of virtualenv! (https://bugs.kali.org/view.php?id=3245 is the report made by @killswitch-GUI on Kali but I can't reproduce the alleged problem)

**Comment by killswitch-GUI** [comment] 2016-04-23 03:57
@lgcambero @FastandLight Issues has been confirmed by Kali. At this point unistall python-futures, remove python-configparser.  @rhertzog thanks for getting this issue raised

**Comment by killswitch-GUI** [comment] 2016-05-11 16:53
This issue had been fixed in python futures! Closing issue.

**Closed by killswitch-GUI** 2016-05-11 16:53 UTC
Labels: bug
